# Generated by Django 4.2.11 on 2024-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=200)),
                ('action_place', models.CharField(blank=True, max_length=100)),
                ('action_category', models.CharField(max_length=100)),
                ('action_region', models.CharField(max_length=100)),
                ('action_about', models.TextField(blank=True)),
                ('action_coordinates', models.CharField(max_length=50)),
                ('action_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('action_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
